# Generated by Django 4.1.3 on 2022-11-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='session_time',
            field=models.TextField(blank=True, default=False),
        ),
    ]
