# Generated by Django 4.1.3 on 2022-11-19 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_assignment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
