# Generated by Django 4.1.7 on 2023-03-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_answer_session_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='marks',
            field=models.TextField(blank=True, default=0),
        ),
    ]
