# Generated by Django 4.1.3 on 2022-11-19 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_assignment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_on']},
        ),
    ]
