# Generated by Django 4.1.3 on 2022-11-24 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_alter_assignment_status_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='assignment_in',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='lab.assignment'),
        ),
    ]
